language: generic

matrix:
  include:
    - os: linux
      env: TARGET=android
    - os: osx
      osx_image: xcode10.2
      env: TARGET=ios
    - os: osx
      osx_image: xcode10.2
      env: TARGET=macos
    - os: windows
      env: TARGET=win64
    - os: linux
      env: TARGET=linux_x86_64

before_script:
  - |
    if [[ $TARGET == android ]]; then
        if [[ ! -e android-ndk-r16b ]]; then
            curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
            unzip -oq android-ndk-r16b-linux-x86_64.zip
            rm android-ndk-r16b-linux-x86_64.zip
        fi
        export ANDROID_NDK_r16b="$HOME/android-ndk-r16b"
    fi

script:
  - bash ./build-ogg.sh
  - bash ./build-opus.sh

before_deploy:
  - mv _bin "binary-${TARGET}-${TRAVIS_TAG}"
  - zip "binary-${TARGET}-${TRAVIS_TAG}.zip" -r "binary-${TARGET}-${TRAVIS_TAG}"

deploy:
  provider: releases
  api_key:
    secure: DTzhq2qvymIfrY3dG5/O3IEbHy/k4WqIBGuBOeKWl0LBrZIrELo8+S/RU5uePPHa2EAY70aK/AQAqpZHCIfSW/MQXQ1fcFpXiJ0W0LfaTYYHom73UdTwbWnMBW4ADgNusgzg9UvmLZJQ1oqC7c2kuYE/LMISwE97akPhtKdtGA20cbdTrLqUXIYBky5b9LQK8MSF/sR7QvEzBJrO5OIwB2/pKYJgMb5N89ypUCvOxs/WDjs1GEtEOE8u8ldpKpkP2KEmK/FSLgYcPfJ1LyrTrAw7jLsIZtk5DE9u22SW4HvDKMtUd4Hu7MKf34PqbhoRwf1mQV+YCXX89Zq1tl5SvrtvChAW4u9ophHgNYAEq6jpxf4ApL06cV9yKfICu9bG9QQC7y62tKYvV3S8HFtsxy9dnSXxh9gOjZ1HW7SQKFwbyXXrLJHmHCn2SxnUcskMnK2Zy7hBzf03S5vtf6gQdB6zHWXD3p21vFElW7l2tjJ0o1bS+3e26Rqay/wOBFMKRq/MTZh7C6rKznPxhYZyYrs6EWKzHXDRpWs0CGwI29tcfe8386Pk6MfLdoVT50nbkoWgZV0yyOz4l6ycTcFwzFpA85GhPHJDXlANaSaTydNJq7tIllXfTo5RrkW+/am2es5Zc6hrJUwBrwfnGleyNevVhqctOXZvbEmj2wZJc3A=
  file: binary-${TARGET}-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: mezum/unity-native-plugin-build
    tag: true

cache:
  directories:
    - android-ndk-r16b
