language: bash

matrix:
  include:
    - os: linux
      env: TARGET=android
    - os: osx
      osx_image: xcode10.2
      env: TARGET=ios
    - os: osx
      osx_image: xcode10.2
      env: TARGET=macos
    - os: windows
      env: TARGET=win64
    - os: linux
      env: TARGET=linux_x86_64

before_script:
  - |
    if [[ $TARGET == android ]]; then
        if [[ ! -e android-ndk-r16b ]]; then
            curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
            unzip -oq android-ndk-r16b-linux-x86_64.zip
            rm android-ndk-r16b-linux-x86_64.zip
        fi
        export ANDROID_NDK_r16b="$HOME/android-ndk-r16b"
    fi

script:
  - bash ./build-ogg.sh
  - bash ./build-opus.sh

before_deploy:
  - mv _bin "binary-${TARGET}-${TRAVIS_TAG}"
  - zip "binary-${TARGET}-${TRAVIS_TAG}.zip" -r "binary-${TARGET}-${TRAVIS_TAG}"

deploy:
  provider: releases
  api_key:
    secure: AH8uvRc4ou6BPptYqR0szOgSXOh4KmX236IPtr3t1NmIxcmr1BkXNF/AK7+Qb9Al9s1kUyeYNjMP/xsU8+78Cn+ukjIqJtUOPdJqR95vjehFmEk1vFa507MH/ybnHa25Z66ghfVShFt/QOrSgLfNil3kbMjFCYl+CVAPRCMnzAOpmldLLlnQzTrdRcjmPRJ66/fAtDRrkQagwotho+BFNPBW2+NJJw6eqsR7zWYADFjKxtjK/fqrJ0nURnUbIvKcSisR3PQzXYGpE8cbKw0sGFXhihUPl7bslSs8dDeA3XDjKQPJnapLOa/68bVpk3XKeKGlcgU5zZRxqfSs9wtvzxNjvu1RT6ivsDN57lcZ3fc7EdHwgIz+3USKJktnzBTQi7X4IcGT3KUI5MrND8ZvoyDOuSV0notgaHqgtlzWmBjhJ+g/1oHuz85lSN00cZmJtYjrWecK0oiaOLuZ5zUCWYhyPUhjAepyj5sQBGvL4Nn7ICmnQ/n7mUN4dS+QlhUBcwTKrIs5NGtDKdj0hZlB4NR4Azr96ZyUFk+oWy6bcJyXaizjcAQ7X+yKVWS4pBDjiofWmxAb9P92BTJ+Jr5PEfR0aon6GMlYn7yXq0KwLXXnhM/88l4HE2By7GN9LmVmxjGR6jGYmw0t2SBWLwj0B67zG5GIH+y9TAL374dfU9M=
  file: binary-${TARGET}-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: mezum/unity-native-plugin-build
    tag: true

cache:
  directories:
    - android-ndk-r16b
